version: '3.1'

volumes:
  server_on_ship_mongo_data:
    external: true

services:
  port-srv:
    image: golang:latest
    env_file:
      - docker-compose.env
    volumes:
      - .:/go/src/github.com/ic2hrmk/skeleton/
    working_dir: /go/src/github.com/ic2hrmk/skeleton/
    command: go run ./app/base/entry.go --address=:10001
    restart: always
    depends_on:
      - mongo

  #
  # 3-rd parties
  #
  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - server_on_ship_mongo_data:/data/db

  mongo_express:
    image: mongo-express
    ports:
      - 7017:8081
    links:
      - mongo
    logging:
      driver: none
    depends_on:
      - mongo

  nginx:
    image: "nginx:latest"
    ports:
      - "8081:80"
    volumes:
      - ./docker-compose.nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: none
