[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.8.1"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-validation"
  version = "3.5.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[prune]
  go-tests = true
  unused-packages = true
